{% set name = "rocrate-inveniordm" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rocrate_inveniordm-{{ version }}.tar.gz
  sha256: ae5764f70572f990f10f658891e34118c25679262868f7e693e38b7eadf03cda

build:
  entry_points:
    - rocrate_inveniordm = rocrate_inveniordm.deposit:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.31.0,<3.0.0
    - python-dateutil >=2.9.0,<3.0.0
    - python-iso639 >=2023.6.15
    - pytz >=2024.1.0

test:
  imports:
    - rocrate_inveniordm
    - rocrate_inveniordm.deposit
    - rocrate_inveniordm.mapping
    - rocrate_inveniordm.mapping.converter
    - rocrate_inveniordm.upload
    - rocrate_inveniordm.upload.uploader
  commands:
    - pip check
    - rocrate_inveniordm --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.researchobject.org/ro-crate/
  summary: Upload RO-Crates to InvenioRDM and automatically fill the metadata. Supports any InvenioRDM instance, including Zenodo.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - elichad
    - stain
